services:
  - type: web
    name: bot-spx
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python web_main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: LIBSQL_URL
        sync: false
      - key: LIBSQL_AUTH_TOKEN
        sync: false
